In [1]:
import sys
import os
sys.path.append(os.path.abspath('..'))

In [2]:
import pandas as pd
import numpy as np

In [3]:
folder_path = "../data/raw/tomato/"
file_names = os.listdir(folder_path)

In [4]:
production_reports = []
for file in file_names:
    df = pd.read_csv(folder_path + file,encoding = 'latin1')
    production_reports.append(df)

production_reports = pd.concat(production_reports,axis=0)

In [5]:
production_reports.head()

,Fecha Transplante,Fecha TransplanteTxt,AÃ±oSiembra,Productor,Productor.1,Ha,Fecha Recibo,FechaRecibo txt,AÃ±o Recibo,Semana Recibo,Kilos,Clase,Tipo,Variedad,Parcela,Lote,Brix,AñoSiembra,Año Recibo
0,19/03/2021,19-Mar-21,2021.0,VAP,San Vicente,0.976,9/6/2021,9-Jun-21,2021.0,24,225.0,BSUF,Uva Roja ...,AmaÃ­,V02,27,7.8,NaN,NaN
1,19/03/2021,19-Mar-21,2021.0,VAP,San Vicente,0.976,14/06/2021,14-Jun-21,2021.0,25,565.0,BSUF,Uva Roja ...,AmaÃ­,V02,27,7.0,NaN,NaN
2,19/03/2021,19-Mar-21,2021.0,VAP,San Vicente,0.976,18/06/2021,18-Jun-21,2021.0,25,1881.0,BSUF,Uva Roja ...,AmaÃ­,V02,27,9.0,NaN,NaN
3,19/03/2021,19-Mar-21,2021.0,VAP,San Vicente,0.976,19/07/2021,19-Jul-21,2021.0,30,1320.0,BSUF,Uva Roja ...,AmaÃ­,V02,27,11.4,NaN,NaN
4,19/03/2021,19-Mar-21,2021.0,VAP,San Vicente,0.976,25/06/2021,25-Jun-21,2021.0,26,908.0,BSUF,Uva Roja ...,AmaÃ­,V02,27,8.4,NaN,NaN

In [6]:
production_reports.columns = ['TransplantDate', 'Fecha TransplanteTxt', 'AÃ±oSiembra', 'ProducerCode',
       'Productor.1', 'Ha', 'DateRecieved', 'FechaRecibo txt', 'AÃ±o Recibo',
       'WeekRecieved', 'Kilos', 'Class', 'Type', 'Variety', 'Parcel',
       'Lot', 'Brix', 'AñoSiembra', 'Año Recibo']

In [7]:
df = production_reports[['TransplantDate','ProducerCode','Ha','DateRecieved','WeekRecieved','Kilos','Class','Type','Variety','Parcel','Lot','Brix']]

In [8]:
df['Type'] = df['Type'].str.rstrip()

/var/folders/fb/78nymm551yn_7vm06j_3sk9w0000gn/T/ipykernel_73076/4090726755.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Type'] = df['Type'].str.rstrip()

In [9]:
df['Parcel'] = df['Parcel'].str.upper()
df['Type'] = df['Type'].str.title()
df['Variety'] = df['Variety'].str.title()

/var/folders/fb/78nymm551yn_7vm06j_3sk9w0000gn/T/ipykernel_73076/509442144.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Parcel'] = df['Parcel'].str.upper()
/var/folders/fb/78nymm551yn_7vm06j_3sk9w0000gn/T/ipykernel_73076/509442144.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Type'] = df['Type'].str.title()
/var/folders/fb/78nymm551yn_7vm06j_3sk9w0000gn/T/ipykernel_73076/509442144.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Variety'] = df['Variety'].str.title()

In [10]:
df['TransplantDate'] = pd.to_datetime(df['TransplantDate'], dayfirst=True)
df['DateRecieved'] = pd.to_datetime(df['DateRecieved'], dayfirst=True)

/var/folders/fb/78nymm551yn_7vm06j_3sk9w0000gn/T/ipykernel_73076/3674227854.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['TransplantDate'] = pd.to_datetime(df['TransplantDate'], dayfirst=True)
/var/folders/fb/78nymm551yn_7vm06j_3sk9w0000gn/T/ipykernel_73076/3674227854.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['DateRecieved'] = pd.to_datetime(df['DateRecieved'], dayfirst=True)

In [11]:
df['Variety'] = df['Variety'].replace({
    'Amaã\xad': 'Amaí',                    # Fix encoding issue
    'Beby Black Plum': 'Baby Black Plum', # Fix typo
    'Top-2204': 'Top 2204',               # Standardize format
    'Top-2245': 'Top 2245'                # Standardize format
})

/var/folders/fb/78nymm551yn_7vm06j_3sk9w0000gn/T/ipykernel_73076/3797172619.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Variety'] = df['Variety'].replace({

In [12]:
df = df[df['Type'] != 'Pruebas']

In [13]:
df['WeekTransplanted'] = df['TransplantDate'].dt.isocalendar().week

In [14]:
df['WeekAfterTransplant'] = (df['WeekRecieved'].astype(int) - df['WeekTransplanted'].astype(int)) % 52

In [15]:
df

,TransplantDate,ProducerCode,Ha,DateRecieved,WeekRecieved,Kilos,Class,Type,Variety,Parcel,Lot,Brix,WeekTransplanted,WeekAfterTransplant
0,2021-03-19,VAP,0.976,2021-06-09,24,225.0,BSUF,Uva Roja,Amaí,V02,27,7.8,11,13
1,2021-03-19,VAP,0.976,2021-06-14,25,565.0,BSUF,Uva Roja,Amaí,V02,27,7.0,11,14
2,2021-03-19,VAP,0.976,2021-06-18,25,1881.0,BSUF,Uva Roja,Amaí,V02,27,9.0,11,14
3,2021-03-19,VAP,0.976,2021-07-19,30,1320.0,BSUF,Uva Roja,Amaí,V02,27,11.4,11,19
4,2021-03-19,VAP,0.976,2021-06-25,26,908.0,BSUF,Uva Roja,Amaí,V02,27,8.4,11,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31663,2020-07-28,SAB,0.480,2020-11-11,46,968.0,BSUF,Uva Roja,Amaí,S17,5,7.3,31,15
31664,2020-07-28,SAB,0.480,2020-10-31,44,583.0,BSUF,Uva Roja,Amaí,S17,5,7.6,31,13
31665,2020-07-28,SAB,0.432,2020-11-06,45,990.0,BSUF,Uva Roja,Amaí,S17,6,7.4,31,14
31666,2020-07-28,SAB,0.432,2020-11-20,47,22.0,BSUF,Uva Roja,Amaí,S17,6,7.2,31,16
31667,2020-07-28,SAB,0.432,2020-11-12,46,561.0,BSUF,Uva Roja,Amaí,S17,6,7.2,31,15

In [16]:
meta = df.groupby(['TransplantDate','Parcel','Lot','ProducerCode','Variety','Ha']).agg({'Class': 'first', 'Type': 'first','WeekTransplanted':'first'}).reset_index()

In [17]:
pivoted = df.pivot_table(index=['TransplantDate', 'Parcel', 'Lot', 'ProducerCode', 'Variety','Ha'], columns='WeekAfterTransplant', values='Kilos', aggfunc='sum').fillna(0)

In [18]:
meta['Week_Cos'] = np.cos(2 * np.pi * meta['WeekTransplanted'] / 52)
meta['Week_Sin'] = np.sin(2 * np.pi * meta['WeekTransplanted'] / 52)
meta

,TransplantDate,Parcel,Lot,ProducerCode,Variety,Ha,Class,Type,WeekTransplanted,Week_Cos,Week_Sin
0,2012-03-28,N02,7,OAP,Shiren,0.1330,CHE,Cherry Rojo,13,-0.0,1.0
1,2012-04-11,S03,5,SAB,Honey Bunch,0.1280,BSUF,Uva Amarilla,15,-0.239316,0.970942
2,2012-08-02,Z17,6,ZJL,Felicity,0.6863,CHE,Cherry Rojo,31,-0.822984,-0.568065
3,2012-08-23,Z17,2,ZJL,Amaí,0.6525,BSUF,Uva Roja,34,-0.568065,-0.822984
4,2012-08-24,Z17,15,ZJL,Baby Black Plum,0.0450,CHE,Heirloom Cherry,34,-0.568065,-0.822984
...,...,...,...,...,...,...,...,...,...,...,...
4209,2024-07-25,S12,4,SGB,Top 2323,0.1530,CHE,Cherry Rosa,30,-0.885456,-0.464723
4210,2024-07-25,S12,4,SGB,Yoyomo,0.1020,BSUF,Uva Amarilla,30,-0.885456,-0.464723
4211,2024-07-29,S12,7,SGB,King,0.5100,BSUF,Uva Roja,31,-0.822984,-0.568065
4212,2024-07-29,S12,8,SGB,King,0.0306,BSUF,Uva Roja,31,-0.822984,-0.568065
4213,2024-07-29,S12,8,SGB,Tymoty,0.3978,CHE,Cherry Rojo,31,-0.822984,-0.568065

In [19]:
pivoted

WeekAfterTransplant                                             1    2    3   \
TransplantDate Parcel Lot ProducerCode Variety         Ha
2012-03-28     N02    7   OAP          Shiren          0.1330  0.0  0.0  0.0
2012-04-11     S03    5   SAB          Honey Bunch     0.1280  0.0  0.0  0.0
2012-08-02     Z17    6   ZJL          Felicity        0.6863  0.0  0.0  0.0
2012-08-23     Z17    2   ZJL          Amaí            0.6525  0.0  0.0  0.0
2012-08-24     Z17    15  ZJL          Baby Black Plum 0.0450  0.0  0.0  0.0
...                                                            ...  ...  ...
2024-07-25     S12    4   SGB          Top 2323        0.1530  0.0  0.0  0.0
                                       Yoyomo          0.1020  0.0  0.0  0.0
2024-07-29     S12    7   SGB          King            0.5100  0.0  0.0  0.0
                      8   SGB          King            0.0306  0.0  0.0  0.0
                                       Tymoty          0.3978  0.0  0.0  0.0

WeekAfterTransplant                                             4    5    6   \
TransplantDate Parcel Lot ProducerCode Variety         Ha
2012-03-28     N02    7   OAP          Shiren          0.1330  0.0  0.0  0.0
2012-04-11     S03    5   SAB          Honey Bunch     0.1280  0.0  0.0  0.0
2012-08-02     Z17    6   ZJL          Felicity        0.6863  0.0  0.0  0.0
2012-08-23     Z17    2   ZJL          Amaí            0.6525  0.0  0.0  0.0
2012-08-24     Z17    15  ZJL          Baby Black Plum 0.0450  0.0  0.0  0.0
...                                                            ...  ...  ...
2024-07-25     S12    4   SGB          Top 2323        0.1530  0.0  0.0  0.0
                                       Yoyomo          0.1020  0.0  0.0  0.0
2024-07-29     S12    7   SGB          King            0.5100  0.0  0.0  0.0
                      8   SGB          King            0.0306  0.0  0.0  0.0
                                       Tymoty          0.3978  0.0  0.0  0.0

WeekAfterTransplant                                             7     8   \
TransplantDate Parcel Lot ProducerCode Variety         Ha
2012-03-28     N02    7   OAP          Shiren          0.1330  0.0   0.0
2012-04-11     S03    5   SAB          Honey Bunch     0.1280  0.0   0.0
2012-08-02     Z17    6   ZJL          Felicity        0.6863  0.0   0.0
2012-08-23     Z17    2   ZJL          Amaí            0.6525  0.0   0.0
2012-08-24     Z17    15  ZJL          Baby Black Plum 0.0450  0.0   0.0
...                                                            ...   ...
2024-07-25     S12    4   SGB          Top 2323        0.1530  0.0   0.0
                                       Yoyomo          0.1020  0.0   0.0
2024-07-29     S12    7   SGB          King            0.5100  0.0  33.0
                      8   SGB          King            0.0306  0.0   0.0
                                       Tymoty          0.3978  0.0   0.0

WeekAfterTransplant                                              9      10  \
TransplantDate Parcel Lot ProducerCode Variety         Ha
2012-03-28     N02    7   OAP          Shiren          0.1330   0.0    0.0
2012-04-11     S03    5   SAB          Honey Bunch     0.1280   0.0    0.0
2012-08-02     Z17    6   ZJL          Felicity        0.6863   0.0    0.0
2012-08-23     Z17    2   ZJL          Amaí            0.6525   0.0    0.0
2012-08-24     Z17    15  ZJL          Baby Black Plum 0.0450   0.0    0.0
...                                                             ...    ...
2024-07-25     S12    4   SGB          Top 2323        0.1530   0.0    0.0
                                       Yoyomo          0.1020   0.0    0.0
2024-07-29     S12    7   SGB          King            0.5100  88.0    0.0
                      8   SGB          King            0.0306   0.0  143.0
                                       Tymoty          0.3978  36.0  108.0

WeekAfterTransplant                                            ...   31   32  \
TransplantDate Parcel Lot ProducerCode Variety         Ha      ...
2012-03-28     N02    7   OAP          Shiren          0.1330  ...  0.0  0.0
2012-04-11     S03    5   SAB          Honey Bunch     0.1280  ...  0.0  0.0
2012-08-02     Z17    6   ZJL          Felicity        0.6863  ...  0.0  0.0
2012-08-23     Z17    2   ZJL          Amaí            0.6525  ...  0.0  0.0
2012-08-24     Z17    15  ZJL          Baby Black Plum 0.0450  ...  0.0  0.0
...                                                            ...  ...  ...
2024-07-25     S12    4   SGB          Top 2323        0.1530  ...  0.0  0.0
                                       Yoyomo          0.1020  ...  0.0  0.0
2024-07-29     S12    7   SGB          King            0.5100  ...  0.0  0.0
                      8   SGB          King            0.0306  ...  0.0  0.0
                                       Tymoty          0.3978  ...  0.0  0.0

WeekAfterTransplant                                             33   34   35  \
TransplantDate Parcel Lot ProducerCode Variety         Ha
2012-03-28     N02    7   OAP          Shiren          0.1330  0.0  0.0  0.0
2012-04-11     S03    5   SAB          Honey Bunch     0.1280  0.0  0.0  0.0
2012-08-02     Z17    6   ZJL          Felicity        0.6863  0.0  0.0  0.0
2012-08-23     Z17    2   ZJL          Amaí            0.6525  0.0  0.0  0.0
2012-08-24     Z17    15  ZJL          Baby Black Plum 0.0450  0.0  0.0  0.0
...                                                            ...  ...  ...
2024-07-25     S12    4   SGB          Top 2323        0.1530  0.0  0.0  0.0
                                       Yoyomo          0.1020  0.0  0.0  0.0
2024-07-29     S12    7   SGB          King            0.5100  0.0  0.0  0.0
                      8   SGB          King            0.0306  0.0  0.0  0.0
                                       Tymoty          0.3978  0.0  0.0  0.0

WeekAfterTransplant                                             36   37   38  \
TransplantDate Parcel Lot ProducerCode Variety         Ha
2012-03-28     N02    7   OAP          Shiren          0.1330  0.0  0.0  0.0
2012-04-11     S03    5   SAB          Honey Bunch     0.1280  0.0  0.0  0.0
2012-08-02     Z17    6   ZJL          Felicity        0.6863  0.0  0.0  0.0
2012-08-23     Z17    2   ZJL          Amaí            0.6525  0.0  0.0  0.0
2012-08-24     Z17    15  ZJL          Baby Black Plum 0.0450  0.0  0.0  0.0
...                                                            ...  ...  ...
2024-07-25     S12    4   SGB          Top 2323        0.1530  0.0  0.0  0.0
                                       Yoyomo          0.1020  0.0  0.0  0.0
2024-07-29     S12    7   SGB          King            0.5100  0.0  0.0  0.0
                      8   SGB          King            0.0306  0.0  0.0  0.0
                                       Tymoty          0.3978  0.0  0.0  0.0

WeekAfterTransplant                                             39   40
TransplantDate Parcel Lot ProducerCode Variety         Ha
2012-03-28     N02    7   OAP          Shiren          0.1330  0.0  0.0
2012-04-11     S03    5   SAB          Honey Bunch     0.1280  0.0  0.0
2012-08-02     Z17    6   ZJL          Felicity        0.6863  0.0  0.0
2012-08-23     Z17    2   ZJL          Amaí            0.6525  0.0  0.0
2012-08-24     Z17    15  ZJL          Baby Black Plum 0.0450  0.0  0.0
...                                                            ...  ...
2024-07-25     S12    4   SGB          Top 2323        0.1530  0.0  0.0
                                       Yoyomo          0.1020  0.0  0.0
2024-07-29     S12    7   SGB          King            0.5100  0.0  0.0
                      8   SGB          King            0.0306  0.0  0.0
                                       Tymoty          0.3978  0.0  0.0

[4214 rows x 40 columns]

In [20]:
climate_folder_path = "../data/raw/climate/"
climate_file_names = os.listdir(climate_folder_path)

climate_dict = {}
for file in climate_file_names:
    df = pd.read_csv(climate_folder_path + file)
    df.drop(columns = ['Unnamed: 0','0'],inplace = True)
    df.date = pd.to_datetime(df.date)
    loc = file.split("_")[2][:-4]
    climate_dict[loc] = df

In [21]:
climate_dict['OAP']

,date,temperature_2m_max,temperature_2m_min,precipitation_sum,rain_sum,shortwave_radiation_sum,et0_fao_evapotranspiration,sunshine_duration,weather_code,precipitation_hours,wind_speed_10m_max
0,2012-01-01 00:00:00+00:00,26.339499,7.789500,0.0,0.0,13.46,3.480398,33107.477,0.0,0.0,15.844089
1,2012-01-02 00:00:00+00:00,27.139500,8.439500,0.0,0.0,13.38,3.825453,33141.234,0.0,0.0,15.141414
2,2012-01-03 00:00:00+00:00,27.789500,8.789500,0.0,0.0,13.05,3.472074,33178.043,3.0,0.0,13.104197
3,2012-01-04 00:00:00+00:00,27.139500,8.389500,0.0,0.0,13.63,3.741527,33217.832,0.0,0.0,14.707222
4,2012-01-05 00:00:00+00:00,26.489500,8.039500,0.0,0.0,13.33,3.881357,33260.516,3.0,0.0,13.441071
...,...,...,...,...,...,...,...,...,...,...,...
4912,2025-06-13 00:00:00+00:00,30.838000,16.088000,0.0,0.0,32.61,6.991274,48018.860,1.0,0.0,13.125196
4913,2025-06-14 00:00:00+00:00,35.738003,17.487999,0.0,0.0,32.21,7.321948,48036.060,3.0,0.0,16.663374
4914,2025-06-15 00:00:00+00:00,39.538002,15.738000,0.0,0.0,32.97,8.037527,48050.793,0.0,0.0,17.944110
4915,2025-06-16 00:00:00+00:00,39.438000,15.688001,0.0,0.0,32.72,8.424739,48062.926,0.0,0.0,19.523155
4916,2025-06-17 00:00:00+00:00,38.138000,15.938001,0.0,0.0,32.72,8.526429,48072.418,0.0,0.0,19.416653

In [22]:
meta['Year'] = meta['TransplantDate'].dt.year

In [23]:
# Convert climate data dates to timezone-naive
for key in climate_dict:
    climate_dict[key]['date'] = climate_dict[key]['date'].dt.tz_localize(None)

In [24]:
meta['ClimateSeries'] = meta.apply(
    lambda row: climate_dict[row['ProducerCode']].loc[
        (climate_dict[row['ProducerCode']]['date'] >= row['TransplantDate']) & 
        (climate_dict[row['ProducerCode']]['date'] < row['TransplantDate'] + pd.Timedelta(days=100))
    ].reset_index(drop=True).values[:,1:], axis=1
)

In [36]:
meta

0        7
1        5
2        6
3        2
4       15
        ..
4209     4
4210     4
4211     7
4212     8
4213     8
Name: Lot, Length: 4214, dtype: int64

In [26]:
y = pivoted.iloc[meta.index].values

filtering

In [27]:
outliers = meta.copy()

In [28]:
outliers.loc[:,'Total_Kilos'] = y.sum(axis=1)
outliers.loc[:,'Yield'] = outliers.loc[:,'Total_Kilos'] / outliers.loc[:,'Ha']
outliers.loc[:,'FirstHarvest'] = [np.argmax(row > 0) if np.any(row > 0) else np.nan for row in y]
outliers.loc[:,'Num_Harvests'] = [np.sum(row > 0) if np.any(row > 0) else np.nan for row in y]
outliers.loc[:,'Coverage'] = outliers.loc[:,'Num_Harvests'] + outliers.loc[:,'FirstHarvest']
outliers.loc[:,'EndHarvest'] = [np.max(np.nonzero(row)[0]) if np.any(row > 0) else np.nan for row in y]
outliers.loc[:,'Harvest_Duration'] = outliers.loc[:,'EndHarvest'] - outliers.loc[:,'FirstHarvest']

In [29]:
from scipy.stats import zscore

# Convert specified columns to z-scores
columns_to_convert = ['Total_Kilos', 'Yield', 'FirstHarvest', 'Num_Harvests', 'Coverage', 'EndHarvest', 'Harvest_Duration']
outliers[columns_to_convert] = outliers[columns_to_convert].apply(zscore)
# Make the columns 1 if they are outside of [-3, 3]
outliers[columns_to_convert] = outliers[columns_to_convert].apply(lambda x: (x < -3) | (x > 3)).astype(int)

# Create a column called 'outliers' that is the sum of those columns
outliers['outliers'] = outliers[columns_to_convert].sum(axis=1)

In [30]:
goods = outliers.outliers == 0

In [31]:
new_meta = meta[goods].reset_index()
new_y = y[goods]

In [32]:
new_meta.shape

(3952, 14)

In [33]:
new_y.shape

(3952, 40)

In [37]:
new_mappings = {
    'Variety': {variety: idx for idx, variety in enumerate(new_meta['Variety'].unique())},
    'Class': {cls: idx for idx, cls in enumerate(new_meta['Class'].unique())},
    'Type': {typ: idx for idx, typ in enumerate(new_meta['Type'].unique())},
    'ProducerCode': {code: idx for idx, code in enumerate(new_meta['ProducerCode'].unique())},
    'Parcel': {parcel: idx for idx, parcel in enumerate(new_meta['Parcel'].unique())},
    'Lot': {int(lot): idx for idx, lot in enumerate(new_meta['Lot'].unique())}
}

In [43]:
new_mappings['Lot'].keys()

dict_keys([7, 6, 2, 5, 4, 8, 11, 10, 3, 9, 29, 15, 19, 32, 56, 26, 1, 38, 43, 44, 47, 16, 23, 24, 31, 37, 61, 55, 58, 67, 50, 63, 66, 30, 64, 53, 60, 54, 59, 25, 57, 12, 13, 18, 20, 27, 28, 17, 21, 48, 49, 52, 46, 51, 36, 39, 34, 35, 33, 40, 14, 22, 62, 45, 69, 70, 41, 42, 72, 73, 68, 71, 65, 74, 75])

In [38]:
import json

# Save new_mappings as a JSON file
with open('mappings.json', 'w') as json_file:
    json.dump(new_mappings, json_file)

In [44]:
df = pd.DataFrame(new_y)
df.to_csv('y.csv', index=False)

In [45]:
new_meta.to_json('meta.json', orient='split')